version: '3.4'

services:
  webapi:
    build: .
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapi.pfx
    volumes:
      - /home/fit/.aspnet/https:/https:ro
      - /home/fit/.microsoft/usersecrets/nekakavSecret